import pandas as pd
import os

def generate_reports(df_today, exchange_rate):
    """HTML 리포트와 일자별 마크다운을 생성 (CSS 분리 버전)"""
    
    now = pd.Timestamp.now('Asia/Seoul')
    date_str = now.strftime('%Y-%m-%d')
    time_str = now.strftime('%Y-%m-%d %H:%M:%S')

    # --- 1. 데이터 포맷팅 ---
    df_html = df_today.copy()
    
    for col in ['투자원금(₩)', '평가금액(₩)', '평가손익(₩)', '전일대비 변동폭(₩)']:
        df_html[col] = df_html[col].apply(lambda x: f"₩{int(x):,}")
    
    df_html['수익률(%)'] = df_html['수익률(%)'].apply(
        lambda x: f"<span class='pos'>+{(float(x)*100):.2f}%</span>" if x > 0 
        else f"<span class='neg'>{(float(x)*100):.2f}%</span>" if x < 0 else "0.00%"
    )

    # --- 2. index.html 생성 (외부 style.css 연결) ---
    html_table = df_html.to_html(index=False, classes='asset-table', escape=False)
    
    html_content = f"""
    <!DOCTYPE html>
    <html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>일일 자산 리포트 ({date_str})</title>
        <link rel="stylesheet" href="style.css">
    </head>
    <body>
        <h2>📊 일일 자산 리포트</h2>
        <div class="summary-header">
            <p>🕒 <strong>업데이트:</strong> {time_str} (KST)</p>
            <p>💵 <strong>적용 환율:</strong> 1달러 = <strong>{exchange_rate:,.2f}원</strong></p>
        </div>
        {html_table}
        <p style="text-align:center; color:#95a5a6; font-size:12px; margin-top:30px;">
            This report is automatically generated by GitHub Actions.
        </p>
    </body>
    </html>
    """
    
    with open("index.html", "w", encoding="utf-8") as f:
        f.write(html_content)

    # --- 3. 일자별 마크다운 생성 (기록 저장용) ---
    if not os.path.exists('reports'):
        os.makedirs('reports')
    
    md_content = f"# 📅 자산 기록 ({date_str})\n\n"
    md_content += f"- **업데이트 시간:** {time_str}\n"
    md_content += f"- **적용 환율:** 1달러 = {exchange_rate:,.2f}원\n\n"
    md_content += "### 💰 자산 요약\n\n"
    
    df_md = df_today.copy()
    df_md['수익률(%)'] = (df_md['수익률(%)'] * 100).round(2).astype(str) + "%"
    md_content += df_md.to_markdown(index=False)
    
    with open(f"reports/{date_str}.md", "w", encoding="utf-8") as f:
        f.write(md_content)
    
    print(f"✅ 리포트 생성 완료 (index.html, reports/{date_str}.md)")
